server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: # 为空
    pool:
      max-active: 8 # 连接池最大连接数
      max-wait: -1 # 连接池最大阻塞等待时间
      max-idle: 8 # 连接池最大空闲连接
      min-idle: 0 # 连接池最小空闲连接
    timeout: 300ms # 连接超时时间（毫秒）

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

logging:
  level:
    com:
      peter:
        mapper: debug
